dpi-aware=no
width=50
line-height=24
font=Zed Mono NF:weight=medium:size=18
fields=name,generic,comment,categories,filename,keywords
terminal=alacritty -e
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=yes

[dmenu]

# catppuccin mocha
[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=b4befeff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=b4befeff
counter=7f849cff
border=b4ccccff
