(($+commands[fastfetch])) && [ ! "$ZED_TERM" ] && fastfetch

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="robbyrussell"
plugins=(golang git arduino-cli docker)

source $ZSH/oh-my-zsh.sh

DATA_DIR=$([ -d "$XDG_DATA_HOME" ] && printf "$XDG_DATA_HOME" || printf "$HOME/.local/share")

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ ! -d "$NVM_DIR" ]; then
  export NVM_DIR="$DATA_DIR/nvm"
  [ ! -d "$NVM_DIR" ] && mkdir -p "$NVM_DIR"
  [ -d "/usr/share/nvm" ] && {
    source /usr/share/nvm/nvm.sh
    source /usr/share/nvm/bash_completion
  }
fi

export GOPATH="$DATA_DIR/go"
export PATH=$PATH:$HOME/.local/bin:$GOPATH/bin:$HOME/.cargo/bin
export MANPAGER='nvim +Man!'

# make sure if command is exists
(($+commands[fzf])) && source <(fzf --zsh)
(($+commands[zoxide])) && eval "$(zoxide init zsh)"
(($+commands[oh-my-posh])) && eval "$(oh-my-posh init zsh --config $HOME/.omp.json)"

# load functions and aliases
[ -x "$HOME/.functions.sh" ] && source "$HOME/.functions.sh"
[ -x "$HOME/.aliases.sh" ] && source "$HOME/.aliases.sh"

