export ZSH="$HOME/.oh-my-zsh"

plugins=(golang git)

ZSH_THEME="fishy"
[ -d "$ZSH" ] && source $ZSH/oh-my-zsh.sh || true

DATA_DIR=$([ -d "$XDG_DATA_HOME" ] && printf "$XDG_DATA_HOME" || printf "$HOME/.local/share")

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ ! -d "$NVM_DIR" ]; then
  export NVM_DIR="$DATA_DIR/nvm"
  [ ! -d "$NVM_DIR" ] && mkdir -p "$NVM_DIR"
  [ -d "/usr/share/nvm" ] && {
    source /usr/share/nvm/nvm.sh
    source /usr/share/nvm/bash_completion
  }
fi

export GOPATH="$DATA_DIR/go"
export PATH=$PATH:$HOME/.local/bin:$GOPATH/bin:$HOME/.cargo/bin:~/.bun/bin:$HOME/Apps/android-studio-sdk/flutter-stable/bin
export MANPAGER='nvim +Man!'

# make sure if command is exists
(($+commands[fzf])) && source <(fzf --zsh) || true
(($+commands[zoxide])) && eval "$(zoxide init zsh)" || true
(($+commands[oh-my-posh])) && eval "$(oh-my-posh init zsh --config $HOME/.omp.json)" || true

# load functions and aliases
[ -x "$HOME/.functions.sh" ] && source "$HOME/.functions.sh" || true
[ -x "$HOME/.aliases.sh" ] && source "$HOME/.aliases.sh" || true
[ -d "$HOME/.venv" ] && source "$HOME/.venv/bin/activate" || true
