# xrender | glx
backend = "glx";

shadow = false;
fading = false;
blur-background = false;
corner-radius = 0;

vsync = true;

unredir-if-possible = true; # let fullscreen apps bypass the compositor

use-damage = true;            # repaint only when needed
detect-client-opacity = false;
detect-rounded-corners = false;
detect-transient = false;

log-level = "info";

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1.0; focus = true; };
  dock = { shadow = false; opacity = 1.0; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; shadow = false; };
  dropdown_menu = { opacity = 1.0; shadow = false; };
  normal = { fade = false; shadow = false; };
};
