$auth_agent = org.kde.polkit-kde-authentication-agent-1|polkit-gnome-authentication-agent-1

windowrulev2 = size 40% 70%,class:pavucontrol

windowrulev2 = size 60% 80%,title:(Task Manager - Google Chrome)

windowrulev2 = size 1550 980,title:(New Incognito Tab - Google Chrome)

windowrulev2 = size 60% 80%,class:com.github.wwmm.easyeffects

windowrulev2 = size 60% 80%,title:DevTools.*

windowrulev2 = size 60% 80%,title:(Open File)|(Save File)|(Open Files)

windowrulev2 = size 1024 700,class:org.kde.dolphin

windowrulev2 = move 60 75,class:org.gnome.Nautilus
windowrulev2 = size 985 725,class:org.gnome.Nautilus

windowrulev2 = size 880 790,class:org.pulseaudio.pavucontrol

windowrulev2 = size 1024 700,class:xdg-desktop-portal-gtk

windowrulev2 = opacity 0.86,class:dev.zed.*
windowrulev2 = size 96%,class:dev.zed.*

windowrulev2 = opacity 0.75,class:code-url-handler|Code
windowrulev2 = nodim,class:code-url-handler|Code
windowrulev2 = noshadow,class:code-url-handler|Code

windowrulev2 = size 98%,class:Alacritty
windowrulev2 = opacity 0.86,class:Alacritty

windowrulev2 = size 95%,class:net.lutris.Lutris,title:Lutris
windowrulev2 = size 50%,class:net.lutris.Lutris,title:Log.*

windowrulev2 = size 80% 75%,class:file-chooser

# disable blur for specific windows
$CLASS_NAMES_1 = google-chrome|discord|spotify
windowrulev2 = noblur,class:$CLASS_NAMES_1
windowrulev2 = nodim,class:$CLASS_NAMES_1
windowrulev2 = noshadow,class:$CLASS_NAMES_1

# games window rules
$GAMES_1 = gamescope|osu!|pcsx2-qt
windowrulev2 = immediate,class:$GAMES_1
windowrulev2 = noblur,class:$GAMES_1
windowrulev2 = noanim,class:$GAMES_1
windowrulev2 = nodim,class:$GAMES_1
windowrulev2 = noborder,class:$GAMES_1
windowrulev2 = noshadow,class:$GAMES_1
windowrulev2 = fullscreen,class:$GAMES_1

windowrulev2 = float,class:.*
