#!/bin/sh

# wallpaper
feh --bg-fill ~/.wallpaper.jpg

# keyboard
setxkbmap us

# x11 compositor
picom -b

# clipboard history
clipcatd &

volumeicon &

SCRIPTS="$HOME/.config/icewm/scripts"

. "$SCRIPTS/xidlehook.sh"
